version: '3.7'
services:
  backend:
    container_name: nestjs-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - dev-db
    env_file:
      - .env

  dev-db:
    image: postgres:14.4-alpine
    container_name: nestjs-dev-db
    restart: always
    ports:
      - 5431:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  test-db:
    image: postgres:14.4-alpine
    container_name: nestjs-test-db
    ports:
      - 5435:5432
    env_file:
      - .env.test
volumes:
  postgres:
    name: nestjs-db
